name: Gashapon Monitor
on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Execution mode (check / summary_tokyo / summary_chiba)'
        required: false
        default: 'check'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.12'}
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          LINE_TOKEN_TOKYO: ${{ secrets.LINE_TOKEN_TOKYO }}
          GROUP_ID_TOKYO: ${{ secrets.GROUP_ID_TOKYO }}
          LINE_TOKEN_CHIBA: ${{ secrets.LINE_TOKEN_CHIBA }}
          GROUP_ID_CHIBA: ${{ secrets.GROUP_ID_CHIBA }}
          RUN_MODE: ${{ github.event.inputs.mode }}
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add notified_shops.json tracked_products.json
          git commit -m "Update notified shops and tracked products" || echo "No changes to commit"
          
          for i in {1..5}; do
            git pull --rebase origin main && git push && break
            echo "衝突を検知したため、3秒後に再試行します..."
            sleep 3
          done
